Uc 68.email verification
Ukrainian-Culture/UC.Backend pull request #22
Opened 2023-01-23 12:22 UTC by d4-5

2023-01-23 15:20 UTC, DanylchenkoKateryna requested changes
change id from string to Guid
check whether result failed in ConfirmEmailAsync method
remove word "Async" from tests name
create different tests to invalid user and code

2023-01-24 16:45 UTC, pflofif approved these changes

2023-01-24 17:29 UTC, PetroHorokh requested changes
Change attribute routing of SignUp controller to it starting with capital letter

2023-01-24 17:39 UTC, PetroHorokh approved these changes

2023-01-24 21:01 UTC, KhrystynaHihliuk approved these changes

2023-01-24 22:12 UTC, DanylchenkoKateryna approved these changes

2023-01-24 22:31 UTC, merged